apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: s4s3bp17v-go 
  janus-idp.io/tekton: s4s3bp17v-go
  backstage.io/kubernetes-id: s4s3bp17v-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: s4s3bp17v-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml